markdown: rdiscount
pygments: true
permalink: /posts/:title.html
auto: true
rdiscount:
  extensions: [smart]

title: Tom's Blog
author:
  name: Tang
  email: 409044065@qq.com
  github: tangzhenquan

production_url: http://tangzhenquan.github.io/

baseurl: /
